# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TestCopeCommon/TestCopeCommon.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack
    - name: Publish
      run: dotnet nuget push "*.nupkg" -api-key oy2pznf66iu53jjhj75qz4i7tmfmxnhuhomp7cfidsizrq --source https://api.nuget.org/v3/index.json
